FROM node:14.18.2

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm install

EXPOSE 3000
EXPOSE 9229
ENTRYPOINT ["/app/run-migration.sh"]
CMD [ "npm", "run", "start:dev" ]
