version: '3.7'
services:
  family-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:80
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    name: nest-mongo-db
